export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_WISHLIST_FAILD = "ADD_TO_WISHLIST_FAILD";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_FROM_WISHLIST_FAILD = "REMOVE_FROM_WISHLIST_FAILD";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FAILD = "ADD_TO_CART_FAILD";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const REMOVE_FROM_CART_FAILD = "REMOVE_FROM_CART_FAILD";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"
export const SAVE_SHIPPING_INFO_FAILD = "SAVE_SHIPPING_INFO_FAILD"

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAIL = "PAYMENT_FAIL"

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const MYORDERS_REQUEST = "MYORDERS_REQUEST"
export const MYORDERS_SUCCESS = "MYORDERS_SUCCESS"
export const MYORDERS_FAIL = "MYORDERS_FAIL"

export const GETALL_ORDERS_REQUEST = "GETALL_ORDERS_REQUEST"
export const GETALL_ORDERS_SUCCESSS = "GETALL_ORDERS_SUCCESSS"
export const GETALL_ORDERS_FAIL = "GETALL_ORDERS_FAIL"


export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const CREATE_REPAIR_REQUEST = "CREATE_REPAIR_REQUEST"
export const CREATE_REPAIR_SUCCESS = "CREATE_REPAIR_SUCCESS"
export const CREATE_REPAIR_FAIL = "CREATE_REPAIR_FAIL"


export const CREATE_BANNER_REQUEST = "CREATE_BANNER_REQUEST"
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS"
export const CREATE_BANNER_FAIL = "CREATE_BANNER_FAIL"

export const GETALL_BANNERS_REQUEST = "GETALL_BANNERS_REQUEST"
export const GETALL_BANNERS_SUCCESSS = "GETALL_BANNERS_SUCCESSS"
export const GETALL_BANNERS_FAIL = "GETALL_BANNERS_FAIL"


export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST"
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS"
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL"


export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL"

export const GETALL_CATEGORIES_REQUEST = "GETALL_CATEGORIES_REQUEST"
export const GETALL_CATEGORIES_SUCCESSS = "GETALL_CATEGORIES_SUCCESSS"
export const GETALL_CATEGORIES_FAIL = "GETALL_CATEGORIES_FAIL"


export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL"

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST"
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS"
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL"

export const GETALL_BRANDS_REQUEST = "GETALL_BRANDS_REQUEST"
export const GETALL_BRANDS_SUCCESSS = "GETALL_BRANDS_SUCCESSS"
export const GETALL_BRANDS_FAIL = "GETALL_BRANDS_FAIL"


export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST"
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS"
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL"